config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  resources :categories do
    resources :posts
  end

  root to: 'users#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  KINDS = %w{blog community}

  has_many :posts, dependent: :destroy

  validates :title, :kind, presence: true
  validates :kind, inclusion: { in: KINDS }

  # Kinds methods
  KINDS.each do |kind|
    define_method "#{kind}?" do
      self.kind == kind
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  validates :title, :description, :category_id, presence: true
  validates :category_id, inclusion: { in: Category.ids }
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :mod, :admin]
  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_only
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @posts = @category.posts
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # category /categories
  # category /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categorys_url, notice: 'category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :kind)
    end

    def admin_only
      unless current_user.admin?
        redirect_to :back, alert: "Access denied."
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  # def index
  #   @posts = Post.all
  # end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    post_params['user_id'] = current_user.id
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @category, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
      @category = @post.category
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :category_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def categories
    @categories = Category.all
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.haml
= simple_form_for(@category) do |f|
  .form-inputs
    = f.input :title
    = f.input :kind, as: :select, collection: Category::KINDS, include_blank: false

  .form-actions
    = f.button :submit, class: 'btn btn-primary'
    = link_to 'Back', categories_path, class: 'btn btn-back'

app/views/categories/edit.html.haml
.row
  .col-md-8.col-md-offset-2
    .card
      .card-header
        %h3 Edit category

      .card-content
        .content
          = render 'form'

app/views/categories/index.html.haml
%h1 Listing categories

%table
  %thead
    %tr
      %th Title
      %th
      %th
      %th

  %tbody
    - @categories.each do |category|
      %tr
        %td= category.title
        %td= link_to 'Show', category
        %td= link_to 'Edit', edit_category_path(category)
        %td= link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Post', new_category_path

app/views/categories/new.html.haml
.row
  .col-md-8.col-md-offset-2
    .card
      .card-header
        %h3 New category

      .card-content
        .content
          = render 'form'

app/views/categories/show.html.haml
- if @category.blog?
  = render partial: 'posts/blog', locals: { category: @category, posts: @posts }

- elsif @category.community?
  = render partial: 'posts/community', locals: { category: @category, posts: @posts }

.footer-buttons-wrapper
  = link_to new_category_post_path(@category), class: 'btn-add-post' do
    = fa_icon 'plus-circle', class: 'fa-3x text-primary'

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top{role: 'navigation'}

  .container-fluid

    .navbar-header

      %button.navbar-toggle{'data-target' => '.navbar-ex1-collapse', 'data-toggle' => 'collapse', type: 'button'}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      = link_to 'Timón', root_path, class: 'navbar-brand'

    .collapse.navbar-collapse.navbar-ex1-collapse

      %ul.nav.navbar-nav

        %li{ class: "#{'active' if current_page?(root_path)}" }
          = link_to 'Index', root_path

        - @categories.each do |category|
          %li{ class: "#{'active' if current_page?(category_path(category))}" }
            = link_to category.title, category_path(category)

        %li{ class: "#{'active' if current_page?(users_path)}" }
          = link_to 'Users', users_path

      %ul.nav.navbar-nav.navbar-right

        -# FUTURE FEATURE: Private Messages
        -# --------------------------------
        -# %li.dropdown
        -#   %a.dropdown-toggle{'data-toggle' => 'dropdown', href: '#'}
        -#     = fa_icon 'envelope', text: 'Private Messages'
        -#     %b.caret
        -#   %ul.dropdown-menu.message-dropdown
        -#     %li.message-preview
        -#       %a{:href => '#'}
        -#         .media
        -#           %span.pull-left
        -#             %img.media-object{:alt => '', :src => 'http://placehold.it/50x50'}/
        -#           .media-body
        -#             %h5.media-heading
        -#               %strong John Smith
        -#             %p.small.text-muted
        -#               %i.fa.fa-clock-o
        -#               Yesterday at 4:32 PM
        -#             %p Lorem ipsum dolor sit amet, consectetur...
        -#     %li.message-preview
        -#       %a{:href => '#'}
        -#         .media
        -#           %span.pull-left
        -#             %img.media-object{:alt => '', :src => 'http://placehold.it/50x50'}/
        -#           .media-body
        -#             %h5.media-heading
        -#               %strong John Smith
        -#             %p.small.text-muted
        -#               %i.fa.fa-clock-o
        -#               Yesterday at 4:32 PM
        -#             %p Lorem ipsum dolor sit amet, consectetur...
        -#     %li.message-preview
        -#       %a{:href => '#'}
        -#         .media
        -#           %span.pull-left
        -#             %img.media-object{:alt => '', :src => 'http://placehold.it/50x50'}/
        -#           .media-body
        -#             %h5.media-heading
        -#               %strong John Smith
        -#             %p.small.text-muted
        -#               %i.fa.fa-clock-o
        -#               Yesterday at 4:32 PM
        -#             %p Lorem ipsum dolor sit amet, consectetur...
        -#     %li.message-footer
        -#       %a{:href => '#'} Read All New Messages

        -# FUTURE FEATURE: Notifications
        -# -----------------------------
        -# %li.dropdown
        -#   %a.dropdown-toggle{'data-toggle' => 'dropdown', :href => '#'}
        -#     %i.fa.fa-bell
        -#     %b.caret
        -#   %ul.dropdown-menu.alert-dropdown
        -#     %li
        -#       %a{:href => '#'}
        -#         Alert Name
        -#         %span.label.label-default Alert Badge
        -#     %li
        -#       %a{:href => '#'}
        -#         Alert Name
        -#         %span.label.label-primary Alert Badge
        -#     %li
        -#       %a{:href => '#'}
        -#         Alert Name
        -#         %span.label.label-success Alert Badge
        -#     %li
        -#       %a{:href => '#'}
        -#         Alert Name
        -#         %span.label.label-info Alert Badge
        -#     %li
        -#       %a{:href => '#'}
        -#         Alert Name
        -#         %span.label.label-warning Alert Badge
        -#     %li
        -#       %a{:href => '#'}
        -#         Alert Name
        -#         %span.label.label-danger Alert Badge
        -#     %li.divider
        -#     %li
        -#       %a{:href => '#'} View All

        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{'data-toggle' => 'dropdown', href: '#'}
              = fa_icon 'user', class: 'fa-fw'
              = current_user.name
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to user_path(current_user) do
                  = fa_icon 'user', class: 'fa-fw'
                  Profile
              %li
                = link_to edit_user_registration_path do
                  = fa_icon 'gear', class: 'fa-fw'
                  Settings
              %li.divider
              %li
                = link_to destroy_user_session_path, method: 'delete' do
                  = fa_icon 'power-off', class: 'fa-fw'
                  Log Out
        - else
          %li
            = link_to 'Log in', new_user_session_path
          %li
            = link_to 'Registration', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Timón'
    %meta{name: "description", content: "#{content_for?(:description) ? yield(:description) : 'Timon'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    #wrapper
      = render partial: 'layouts/nav', locals: { categories: categories }
      #page-wrapper
        .container-fluid
          = render 'layouts/messages'
          = yield

app/views/posts/_blog.html.haml
.row
  - @posts.each do |post|
    .col-md-8.col-md-offset-2
      .card
        .card-header
          %h4= post.title
        .card-content
          %p= truncate post.description, length: 1200
        .card-footer
          %p
            = link_to 'Read more', category_post_path(@category, post), class: 'btn btn-sm btn-primary'
            = link_to 'Edit', edit_category_post_path(@category, post), class: 'btn btn-sm btn-warning'
            = link_to 'Destroy', category_post_path(@category, post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'

app/views/posts/_community.html.haml
.row
  - @posts.each do |post|
    .col-sm-6.col-md-6.col-lg-4
      .card
        .card-header
          .title= post.title
        .card-content
          %p= post.description
        .card-footer
          %p
            = link_to 'Edit', edit_category_post_path(@category, post), class: 'btn btn-sm btn-warning'
            = link_to 'Destroy', category_post_path(@category, post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'

app/views/posts/_form.html.haml
= simple_form_for([@category, @post]) do |f|
  .form-inputs
    = f.input :title
    = f.input :description
    = f.association :category
    = f.input :user_id, as: :hidden, value: current_user.id

  .form-actions
    = f.button :submit, class: 'btn btn-primary'
    = link_to 'Back', category_path(@category), class: 'btn btn-back'

app/views/posts/edit.html.haml
.row
  .col-md-8.col-md-offset-2
    .card
      .card-header
        %h3 Editing post

      .card-content
        .content
          = render 'form'

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
.row
  .col-md-8.col-md-offset-2
    .card
      .card-header
        %h2= @post.title

      .card-content
        %p= @post.description

        %p
          .row
            .col-md-6
              %strong Author:
              = @post.user.name
            .col-md-6.right
              %strong Date published:
              = l @post.created_at

      .card-footer
        %p
          = link_to 'Edit', edit_category_post_path(@category, @post), class: 'btn btn-sm btn-warning'
          = link_to 'Destroy', category_post_path(@category, @post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'
          = link_to 'Back', category_path(@category), class: 'btn btn-sm btn-default'

app/views/users/_user.html.haml
%tr
  %td
    = link_to user.name, user
  %td
    = link_to user.email, user
  %td
    = simple_form_for user, html: { class: 'form-inline' } do |f|
      .form-group
        = f.select :role, User.roles.keys.map {|role| [role.titleize,role]}, class: 'form-control'
      = f.submit 'Change Role', class: 'btn btn-default'

  %td
    - unless user == current_user || user.admin?
      = link_to('Delete user', user_path(user), data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-xs btn-danger')

app/views/users/index.html.haml
.card
  .card-header
    %h2 Users

  .card-content
    .table-responsive
      %table.table.table-hover.table-striped
        %thead
          %tr
            %th Name
            %th Email
            %th Role
            %th Delete?

        %tbody
          - @users.each do |user|
            = render user

app/views/users/show.html.haml
.card
  .card-header
    %h2 User

  .card-content
    %p
      %strong Name:
      #{@user.name if @user.name}

    - if current_user.admin?
      %p
        %strong Email:
        #{@user.email if @user.email}

    %p
      %strong Role:
      #{@user.role if @user.role}

app/views/visitors/index.html.haml
%h3 Welcome
%p
  = link_to 'Users:', users_path
  = User.count
  registered